<?php
/** @var \Magebit\PageListWidget\Block\Widget\PageList $block */

$pages = $block->getPages();
?>

<?php if (!empty($pages)): ?>
    <?php if ($title = $block->getTitle()): ?>
        <h3><?= $escaper->escapeHtml($title); ?></h3>
    <?php endif; ?>
    <ul>
        <?php foreach ($pages as $page): ?>
            <?php if ($page->getId()): ?>
                <li>
                    <a href="<?= $escaper->escapeUrl($block->getPageUrl($page->getIdentifier())) ?>">
                        <?= $escaper->escapeHtml($page->getTitle()) ?>
                    </a>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
