<?php
/**
 * This file is part of the Magebit package.
 *
 * @copyright Copyright (c) 2025 Magebit, Ltd. (https://magebit.com/)
 * @license   GNU General Public License ("GPL") v3.0
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
?>
<?php /** @var $block \Magento\Catalog\Block\Product\AbstractProduct */ ?>
<div id="reviews-modal" style="display:none;">
    <div class="modal-inner-content">
    <?= $block->getChildHtml() ?>
    </div>
</div>

<script type="text/x-magento-init">
{
    "#reviews-modal": {
        "Magento_Ui/js/modal/modal": {
            "type": "popup",
            "responsive": true,
            "buttons": []
        }
    }
}
</script>

<script>
require(['jquery'], function($) {
    $(document).ready(function() {
        // Trigger modal when any anchor to #reviews is clicked
        $('.product-reviews-summary a').on('click', function(e) {
            e.preventDefault();
            $('#reviews-modal').modal('openModal');
        });
    });
});
</script>
